update workflow

diff --git a/.github/workflows/production.yml b/.github/workflows/production.yml
--- a/.github/workflows/production.yml
+++ b/.github/workflows/production.yml
@@ -111,13 +111,31 @@ jobs:
         key: ${{ secrets.DIGITALOCEAN_KEY }}
         port: ${{ secrets.DIGITALOCEAN_PORT }}
         script: |
-          sudo apt-get -y update
-          sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
-          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
-          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
-          apt-cache policy docker-ce
-          sudo apt install -y docker-ce
-          sudo systemctl status docker
+          # Check if Docker is installed
+          if ! command -v docker &> /dev/null; then
+            echo "Docker not found. Installing Docker..."
+
+            # Update package index and install dependencies
+            sudo apt-get -y update
+            sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
+            
+            # Add Docker GPG key and repository
+            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
+            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
+            
+            # Update package index again after adding Docker repository
+            sudo apt-get -y update
+            
+            # Install Docker
+            sudo apt install -y docker-ce
+            
+            # Check Docker status
+            sudo systemctl status docker
+          else
+            # Check Docker status
+            sudo systemctl status docker
+            echo "Docker is already installed."
+          fi
 
           # Run Docker Compose with updated environment variables
           sudo docker compose -f ~/crypto-portfolio-manager/docker-compose-prod.yml pull
